-- MySQL Script generated by MySQL Workbench
-- Wed Sep 18 09:16:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema conacyt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conacyt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conacyt` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `conacyt` ;

-- -----------------------------------------------------
-- Table `conacyt`.`af_tipo_bien_contable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`af_tipo_bien_contable` (
  `id_tb_contable` INT NOT NULL AUTO_INCREMENT,
  `tbc_codigo_contable` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `tbc_desc` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `tbc_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id_tb_contable`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`employee` (
  `idemployee` INT NOT NULL AUTO_INCREMENT,
  `empfname` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `empsname` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `emptname` VARCHAR(70) NULL DEFAULT NULL,
  `empfsurname` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `empssurname` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `emptsurname` VARCHAR(70) NULL DEFAULT NULL,
  `empmname` VARCHAR(70) NULL DEFAULT NULL,
  `empdui` VARCHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `empnit` VARCHAR(17) CHARACTER SET 'utf8mb4' NOT NULL,
  `empborndate` DATE NOT NULL,
  `empemail` VARCHAR(170) NULL DEFAULT NULL,
  `empcell` VARCHAR(17) NULL DEFAULT NULL,
  `empoftel` VARCHAR(17) NULL DEFAULT NULL,
  `empecontactname` VARCHAR(70) NULL DEFAULT NULL,
  `empecontactcel` VARCHAR(70) NULL DEFAULT NULL,
  `empcontactkin` VARCHAR(70) NULL DEFAULT NULL,
  `empbgender` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `empfullname` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `empfullnameb` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `emp_idposition` INT NULL DEFAULT NULL,
  `emp_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idemployee`),
  UNIQUE INDEX `emp_idprofession_UNIQUE` (`emp_idposition` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`af_fuente_financiera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`af_fuente_financiera` (
  `id_f_financiera` INT NOT NULL AUTO_INCREMENT,
  `ff_nombre` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `ff_desc` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `ff_e` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id_f_financiera`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`af_d_vida_util`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`af_d_vida_util` (
  `id_vida_util_afd` INT NOT NULL AUTO_INCREMENT,
  `tipo_vida_util_afd` VARCHAR(80) NOT NULL,
  `factor_anual` DECIMAL(18,3) NOT NULL,
  `plazo_vida_util_afd` INT NOT NULL,
  PRIMARY KEY (`id_vida_util_afd`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `conacyt`.`af_activo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`af_activo` (
  `id_activo` INT NOT NULL AUTO_INCREMENT,
  `a_cod_activo_interno_ant` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_codigo_activo` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_id_tb_contable` INT NOT NULL,
  `a_id_f_financiera` INT NOT NULL,
  `a_responsable_id_emp` INT NOT NULL,
  `a_nombre` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_desc` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_tipo` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_color` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_marca` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_modelo` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_n_serie` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_valor_dolar` FLOAT NOT NULL,
  `a_valor_colon` FLOAT NOT NULL,
  `a_fecha_ingreso` DATE NOT NULL,
  `a_fecha_compra` DATE NOT NULL,
  `a_fac_respaldo` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_acta_recepcion` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_ubicacion_desc` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_ubicacion_nivel` VARCHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_uso_estado` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_estado` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `a_vidautil` INT NOT NULL,
  PRIMARY KEY (`id_activo`),
  UNIQUE INDEX `a_codigo_activo_UNIQUE` (`a_codigo_activo` ASC) VISIBLE,
  INDEX `af_contable_idx` (`a_id_tb_contable` ASC) VISIBLE,
  INDEX `af_f_financiera_idx` (`a_id_f_financiera` ASC) VISIBLE,
  INDEX `af_employee_idx` (`a_responsable_id_emp` ASC) VISIBLE,
  INDEX `af_cod` (`a_codigo_activo` ASC) VISIBLE,
  INDEX `af_vida_util_idx` (`a_vidautil` ASC) VISIBLE,
  CONSTRAINT `af_contable`
    FOREIGN KEY (`a_id_tb_contable`)
    REFERENCES `conacyt`.`af_tipo_bien_contable` (`id_tb_contable`),
  CONSTRAINT `af_employee`
    FOREIGN KEY (`a_responsable_id_emp`)
    REFERENCES `conacyt`.`employee` (`idemployee`),
  CONSTRAINT `af_f_financiera`
    FOREIGN KEY (`a_id_f_financiera`)
    REFERENCES `conacyt`.`af_fuente_financiera` (`id_f_financiera`),
  CONSTRAINT `af_vida_util`
    FOREIGN KEY (`a_vidautil`)
    REFERENCES `conacyt`.`af_d_vida_util` (`id_vida_util_afd`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`af_depreciacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`af_depreciacion` (
  `afd_id` INT NOT NULL AUTO_INCREMENT,
  `afd_activo` INT NOT NULL,
  `afd_valor_depreciacion` FLOAT NOT NULL,
  `afd_vida_util` INT NOT NULL,
  `afd_cuota_anual` FLOAT GENERATED ALWAYS AS ((`afd_valor_depreciacion` / `afd_vida_util`)) STORED,
  `afd_cuota_diaria` FLOAT GENERATED ALWAYS AS ((`afd_cuota_anual` / 365)) STORED,
  `afd_fecha_generacion` DATE NOT NULL,
  `afd_fecha_corte` DATE NOT NULL,
  `afd_codigo_informe` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `afd_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`afd_id`),
  INDEX `afd_activo` (`afd_activo` ASC) VISIBLE,
  CONSTRAINT `af_depreciacion_ibfk_1`
    FOREIGN KEY (`afd_activo`)
    REFERENCES `conacyt`.`af_activo` (`id_activo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(10) CHARACTER SET 'utf8mb4' NOT NULL,
  `user_password` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `user_idemp` INT NOT NULL,
  `user_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `idx_user_user_idemp` (`user_idemp` ASC) VISIBLE,
  CONSTRAINT `user-employee`
    FOREIGN KEY (`user_idemp`)
    REFERENCES `conacyt`.`employee` (`idemployee`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`af_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`af_log` (
  `aflog_id` INT NOT NULL AUTO_INCREMENT,
  `aflog_date` DATETIME NOT NULL,
  `aflog_ip` VARCHAR(15) CHARACTER SET 'utf8mb4' NOT NULL,
  `aflog_iduser` INT NOT NULL,
  `aflog_action` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `aflog_desc` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `aflog_idaf` INT NOT NULL,
  PRIMARY KEY (`aflog_id`),
  INDEX `aflog_iduser` (`aflog_iduser` ASC) VISIBLE,
  INDEX `aflog_idaf` (`aflog_idaf` ASC) VISIBLE,
  CONSTRAINT `af_log_ibfk_2`
    FOREIGN KEY (`aflog_idaf`)
    REFERENCES `conacyt`.`af_activo` (`id_activo`),
  CONSTRAINT `af_log_ibfk_3`
    FOREIGN KEY (`aflog_iduser`)
    REFERENCES `conacyt`.`user` (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`company` (
  `idcompany` INT NOT NULL AUTO_INCREMENT,
  `compname` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `compdesc` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `compsr` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `compnit` VARCHAR(17) CHARACTER SET 'utf8mb4' NOT NULL,
  `compnrc` VARCHAR(20) CHARACTER SET 'utf8mb4' NOT NULL,
  `compborndate` DATE NOT NULL,
  `comp_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idcompany`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`branch` (
  `idbranch` INT NOT NULL AUTO_INCREMENT,
  `brnname` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `brnborndate` DATE NOT NULL,
  `brn_compid` INT NOT NULL,
  `brn_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `brn_email` VARCHAR(30) CHARACTER SET 'utf8mb4' NOT NULL,
  `brn_tel` VARCHAR(14) CHARACTER SET 'utf8mb4' NOT NULL,
  `brn_logo` VARCHAR(255) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idbranch`),
  INDEX `brn_compid` (`brn_compid` ASC) VISIBLE,
  CONSTRAINT `branch_ibfk_1`
    FOREIGN KEY (`brn_compid`)
    REFERENCES `conacyt`.`company` (`idcompany`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`contry`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`contry` (
  `idcontry` INT NOT NULL AUTO_INCREMENT,
  `contryname` VARCHAR(60) CHARACTER SET 'utf8mb4' NOT NULL,
  `contry_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `contry_idmh` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`idcontry`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`department` (
  `iddepartment` INT NOT NULL AUTO_INCREMENT,
  `deptname` VARCHAR(35) NULL DEFAULT NULL,
  `dept_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `dept_idmh` VARCHAR(2) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`iddepartment`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`municipnew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`municipnew` (
  `idmunicipnew` INT NOT NULL AUTO_INCREMENT,
  `munipnewname` VARCHAR(100) NOT NULL,
  `munipnew_e` VARCHAR(1) NOT NULL,
  `munipnew_idmh` VARCHAR(2) NOT NULL,
  `munipnew_iddept` INT NOT NULL,
  PRIMARY KEY (`idmunicipnew`),
  INDEX `municipnew_dept_idx` (`munipnew_iddept` ASC) VISIBLE,
  CONSTRAINT `municipnew_dept`
    FOREIGN KEY (`munipnew_iddept`)
    REFERENCES `conacyt`.`department` (`iddepartment`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `conacyt`.`district`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`district` (
  `iddistrict` INT NOT NULL AUTO_INCREMENT,
  `distname` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `dist_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `dist_idmh` VARCHAR(2) CHARACTER SET 'utf8mb4' NOT NULL,
  `dist_idmunicipnew` INT NOT NULL,
  PRIMARY KEY (`iddistrict`),
  INDEX `district_munipnew_idx` (`dist_idmunicipnew` ASC) VISIBLE,
  CONSTRAINT `district_munipnew`
    FOREIGN KEY (`dist_idmunicipnew`)
    REFERENCES `conacyt`.`municipnew` (`idmunicipnew`))
ENGINE = InnoDB
AUTO_INCREMENT = 263
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`municip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`municip` (
  `idmunicip` INT NOT NULL AUTO_INCREMENT,
  `munipname` VARCHAR(200) CHARACTER SET 'utf8mb4' NOT NULL,
  `munip_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `munip_idmh` VARCHAR(2) CHARACTER SET 'utf8mb4' NOT NULL,
  `munip_iddistrict` INT NOT NULL,
  `munip_iddepartment` INT NOT NULL,
  PRIMARY KEY (`idmunicip`),
  INDEX `munip_department_idx` (`munip_iddepartment` ASC) VISIBLE,
  INDEX `munip_disctrict_idx` (`munip_iddistrict` ASC) VISIBLE,
  CONSTRAINT `munip_department`
    FOREIGN KEY (`munip_iddepartment`)
    REFERENCES `conacyt`.`department` (`iddepartment`),
  CONSTRAINT `munip_disctrict`
    FOREIGN KEY (`munip_iddistrict`)
    REFERENCES `conacyt`.`district` (`iddistrict`))
ENGINE = InnoDB
AUTO_INCREMENT = 263
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`branch_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`branch_address` (
  `idbranch_address` INT NOT NULL AUTO_INCREMENT,
  `ba_idcontry` INT NOT NULL,
  `ba_idmunicip` INT NOT NULL,
  `ba_iddisctrict` INT NOT NULL,
  `bacomplement` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `ba_brnid` INT NOT NULL,
  `ba_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idbranch_address`),
  UNIQUE INDEX `ba_idcontry_UNIQUE` (`ba_idcontry` ASC) VISIBLE,
  UNIQUE INDEX `ba_idmunicip_UNIQUE` (`ba_idmunicip` ASC) VISIBLE,
  INDEX `ba_brnid` (`ba_brnid` ASC) VISIBLE,
  CONSTRAINT `branch_address_country`
    FOREIGN KEY (`ba_idcontry`)
    REFERENCES `conacyt`.`contry` (`idcontry`),
  CONSTRAINT `branch_address_ibfk_1`
    FOREIGN KEY (`ba_brnid`)
    REFERENCES `conacyt`.`branch` (`idbranch`),
  CONSTRAINT `branch_address_municip`
    FOREIGN KEY (`ba_idmunicip`)
    REFERENCES `conacyt`.`municip` (`idmunicip`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`emp_address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`emp_address` (
  `idemp_address` INT NOT NULL AUTO_INCREMENT,
  `ea_idcontry` INT NOT NULL,
  `ea_idmunicip` INT NOT NULL,
  `ea_iddisctrict` INT NOT NULL,
  `eacomplement` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `ea_empid` INT NOT NULL,
  `ea_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idemp_address`),
  UNIQUE INDEX `ea_idmunicip_UNIQUE` (`ea_idmunicip` ASC) VISIBLE,
  UNIQUE INDEX `ea_idcontry_UNIQUE` (`ea_idcontry` ASC) VISIBLE,
  INDEX `ea_empid` (`ea_empid` ASC) VISIBLE,
  CONSTRAINT `emp_address_country`
    FOREIGN KEY (`ea_idcontry`)
    REFERENCES `conacyt`.`contry` (`idcontry`),
  CONSTRAINT `emp_address_ibfk_1`
    FOREIGN KEY (`ea_empid`)
    REFERENCES `conacyt`.`employee` (`idemployee`),
  CONSTRAINT `emp_address_municip`
    FOREIGN KEY (`ea_idmunicip`)
    REFERENCES `conacyt`.`municip` (`idmunicip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`modul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`modul` (
  `idmodul` INT NOT NULL AUTO_INCREMENT,
  `modname` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `moddesc` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `modroute` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `modfolder` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `mod_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idmodul`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `menu_idmodul` INT NOT NULL,
  `menuname` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `menudesc` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `menuroute` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `menufolder` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `menu_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idmenu`),
  UNIQUE INDEX `menu_idmodul_UNIQUE` (`menu_idmodul` ASC) VISIBLE,
  CONSTRAINT `menu_modul`
    FOREIGN KEY (`menu_idmodul`)
    REFERENCES `conacyt`.`modul` (`idmodul`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`type_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`type_position` (
  `idtypeposit` INT NOT NULL AUTO_INCREMENT,
  `typepositname` VARCHAR(45) CHARACTER SET 'utf8mb4' NOT NULL,
  `typepositdesc` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `typeposit_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idtypeposit`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`unit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`unit` (
  `idunit` INT NOT NULL AUTO_INCREMENT,
  `unitname` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  `unitintercode` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `unitdesc` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `unitobj` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `unittel` VARCHAR(15) NULL DEFAULT NULL,
  `unitmanager_idemp` INT NULL DEFAULT NULL,
  `unitlocation` VARCHAR(100) NULL DEFAULT NULL,
  `unitborndate` DATE NOT NULL,
  `unitemail` VARCHAR(100) NULL DEFAULT NULL,
  `unit_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `unit_idbranch` INT NOT NULL,
  PRIMARY KEY (`idunit`),
  UNIQUE INDEX `unitmanager_idemp_UNIQUE` (`unitmanager_idemp` ASC) VISIBLE,
  INDEX `unit_branch` (`unit_idbranch` ASC) VISIBLE,
  CONSTRAINT `unit_ibfk_1`
    FOREIGN KEY (`unitmanager_idemp`)
    REFERENCES `conacyt`.`employee` (`idemployee`),
  CONSTRAINT `unit_ibfk_2`
    FOREIGN KEY (`unit_idbranch`)
    REFERENCES `conacyt`.`branch` (`idbranch`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`position` (
  `idposition` INT NOT NULL AUTO_INCREMENT,
  `positname` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `positdesc` VARCHAR(12) NULL DEFAULT NULL,
  `positstate` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `positrequest` VARCHAR(12) NULL DEFAULT NULL,
  `posit_idunit` INT NOT NULL,
  `posit_idtypeposit` INT NOT NULL,
  `posit_nameb` VARCHAR(80) NULL DEFAULT NULL,
  `posit_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `posit_idunitb` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idposition`),
  UNIQUE INDEX `posit_idunit_UNIQUE` (`posit_idunit` ASC) VISIBLE,
  UNIQUE INDEX `posit_idtypeposit_UNIQUE` (`posit_idtypeposit` ASC) VISIBLE,
  INDEX `position_unitb_idx` (`posit_idunitb` ASC) VISIBLE,
  CONSTRAINT `position_typeposition`
    FOREIGN KEY (`posit_idtypeposit`)
    REFERENCES `conacyt`.`type_position` (`idtypeposit`),
  CONSTRAINT `position_unit`
    FOREIGN KEY (`posit_idunit`)
    REFERENCES `conacyt`.`unit` (`idunit`),
  CONSTRAINT `position_unitb`
    FOREIGN KEY (`posit_idunitb`)
    REFERENCES `conacyt`.`unit` (`idunit`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`report` (
  `idreport` INT NOT NULL AUTO_INCREMENT,
  `reptname` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `rept_desc` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `reptroute` VARCHAR(500) CHARACTER SET 'utf8mb4' NOT NULL,
  `reptfolder` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `rept_modul` INT NOT NULL,
  `report_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idreport`),
  INDEX `rept_modul` (`rept_modul` ASC) VISIBLE,
  CONSTRAINT `report_ibfk_1`
    FOREIGN KEY (`rept_modul`)
    REFERENCES `conacyt`.`modul` (`idmodul`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `rolname` VARCHAR(25) CHARACTER SET 'utf8mb4' NOT NULL,
  `roldesc` VARCHAR(100) CHARACTER SET 'utf8mb4' NOT NULL,
  `rol_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`rol_menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`rol_menu` (
  `idrolmenu` INT NOT NULL AUTO_INCREMENT,
  `rolmenu_idrol` INT NOT NULL,
  `rolmenu_idmenu` INT NOT NULL,
  PRIMARY KEY (`idrolmenu`),
  INDEX `rolmenu_menu_idx` (`rolmenu_idmenu` ASC) VISIBLE,
  INDEX `rolmenu_rol_idx` (`rolmenu_idrol` ASC) VISIBLE,
  CONSTRAINT `rolmenu_menu`
    FOREIGN KEY (`rolmenu_idmenu`)
    REFERENCES `conacyt`.`menu` (`idmenu`),
  CONSTRAINT `rolmenu_rol`
    FOREIGN KEY (`rolmenu_idrol`)
    REFERENCES `conacyt`.`rol` (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `conacyt`.`rol_modul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`rol_modul` (
  `idrolmodul` INT NOT NULL AUTO_INCREMENT,
  `rolmodul_idrol` INT NOT NULL,
  `rolmodul_idmodul` INT NOT NULL,
  PRIMARY KEY (`idrolmodul`),
  INDEX `rolmodiul_rol_idx` (`rolmodul_idrol` ASC) VISIBLE,
  INDEX `rolmodul_modul_idx` (`rolmodul_idmodul` ASC) VISIBLE,
  CONSTRAINT `rolmodul_modul`
    FOREIGN KEY (`rolmodul_idmodul`)
    REFERENCES `conacyt`.`modul` (`idmodul`),
  CONSTRAINT `rolmodul_rol`
    FOREIGN KEY (`rolmodul_idrol`)
    REFERENCES `conacyt`.`rol` (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `conacyt`.`rol_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`rol_report` (
  `idrolreport` INT NOT NULL AUTO_INCREMENT,
  `rolreport_idrol` INT NOT NULL,
  `rolreport_idreport` INT NOT NULL,
  PRIMARY KEY (`idrolreport`),
  INDEX `rolreport_report_idx` (`rolreport_idreport` ASC) VISIBLE,
  INDEX `rolreport_rol_idx` (`rolreport_idrol` ASC) VISIBLE,
  CONSTRAINT `rolreport_report`
    FOREIGN KEY (`rolreport_idreport`)
    REFERENCES `conacyt`.`report` (`idreport`),
  CONSTRAINT `rolreport_rol`
    FOREIGN KEY (`rolreport_idrol`)
    REFERENCES `conacyt`.`rol` (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `conacyt`.`solicitud_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`solicitud_log` (
  `slog_id` INT NOT NULL,
  `slog_id_emp` INT NOT NULL,
  `slog_accion` VARCHAR(45) NOT NULL,
  `slog_cod_af` INT NOT NULL,
  `slog_comentario` VARCHAR(255) NULL DEFAULT NULL,
  `slog_codigo_af` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`slog_id`),
  INDEX `slog_employee` (`slog_id_emp` ASC) VISIBLE,
  INDEX `index3` (`slog_cod_af` ASC) VISIBLE,
  CONSTRAINT `slog_activo`
    FOREIGN KEY (`slog_cod_af`)
    REFERENCES `conacyt`.`af_activo` (`id_activo`),
  CONSTRAINT `slog_employee`
    FOREIGN KEY (`slog_id_emp`)
    REFERENCES `conacyt`.`employee` (`idemployee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `conacyt`.`syslog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`syslog` (
  `idsyslog` INT NOT NULL AUTO_INCREMENT,
  `slogdate` DATETIME NOT NULL,
  `slogip` VARCHAR(15) CHARACTER SET 'utf8mb4' NOT NULL,
  `slog_idmodul` INT NOT NULL,
  `slog_idmenu` INT NOT NULL,
  `slogformname` VARCHAR(50) CHARACTER SET 'utf8mb4' NOT NULL,
  `slog_iduser` INT NOT NULL,
  `slogaction` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  `slogdesc` VARCHAR(250) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`idsyslog`),
  INDEX `syslog_modul_idx` (`slog_idmodul` ASC) VISIBLE,
  INDEX `syslog_menu_idx` (`slog_idmenu` ASC) VISIBLE,
  INDEX `syslog_user_idx` (`slog_iduser` ASC) VISIBLE,
  CONSTRAINT `syslog_menu`
    FOREIGN KEY (`slog_idmenu`)
    REFERENCES `conacyt`.`menu` (`idmenu`),
  CONSTRAINT `syslog_modul`
    FOREIGN KEY (`slog_idmodul`)
    REFERENCES `conacyt`.`modul` (`idmodul`),
  CONSTRAINT `syslog_user`
    FOREIGN KEY (`slog_iduser`)
    REFERENCES `conacyt`.`user` (`iduser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `conacyt`.`user_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`user_rol` (
  `id_ur` INT NOT NULL AUTO_INCREMENT,
  `ur_iduser` INT NOT NULL,
  `ur_idrol` INT NOT NULL,
  `ur_e` VARCHAR(1) CHARACTER SET 'utf8mb4' NOT NULL,
  PRIMARY KEY (`id_ur`),
  INDEX `urm_iduser` (`ur_iduser` ASC) VISIBLE,
  INDEX `urm_idrol` (`ur_idrol` ASC) VISIBLE,
  CONSTRAINT `user_rol_ibfk_1`
    FOREIGN KEY (`ur_iduser`)
    REFERENCES `conacyt`.`user` (`iduser`),
  CONSTRAINT `user_rol_ibfk_2`
    FOREIGN KEY (`ur_idrol`)
    REFERENCES `conacyt`.`rol` (`idrol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;

USE `conacyt` ;

-- -----------------------------------------------------
-- Placeholder table for view `conacyt`.`af_depreciacion_v`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conacyt`.`af_depreciacion_v` (`afd_id` INT, `afd_activo` INT, `afd_valor_depreciacion` INT, `afd_vida_util` INT, `afd_cuota_anual` INT, `afd_cuota_diaria` INT, `afd_fecha_generacion` INT, `afd_fecha_corte` INT, `afd_codigo_informe` INT, `afd_depreciacion_acumulada` INT);

-- -----------------------------------------------------
-- View `conacyt`.`af_depreciacion_v`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conacyt`.`af_depreciacion_v`;
USE `conacyt`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `conacyt`.`af_depreciacion_v` AS select `conacyt`.`af_depreciacion`.`afd_id` AS `afd_id`,`conacyt`.`af_depreciacion`.`afd_activo` AS `afd_activo`,`conacyt`.`af_depreciacion`.`afd_valor_depreciacion` AS `afd_valor_depreciacion`,`conacyt`.`af_depreciacion`.`afd_vida_util` AS `afd_vida_util`,`conacyt`.`af_depreciacion`.`afd_cuota_anual` AS `afd_cuota_anual`,`conacyt`.`af_depreciacion`.`afd_cuota_diaria` AS `afd_cuota_diaria`,`conacyt`.`af_depreciacion`.`afd_fecha_generacion` AS `afd_fecha_generacion`,`conacyt`.`af_depreciacion`.`afd_fecha_corte` AS `afd_fecha_corte`,`conacyt`.`af_depreciacion`.`afd_codigo_informe` AS `afd_codigo_informe`,(((to_days(curdate()) - to_days(`conacyt`.`af_depreciacion`.`afd_fecha_generacion`)) / 365) * `conacyt`.`af_depreciacion`.`afd_cuota_anual`) AS `afd_depreciacion_acumulada` from `conacyt`.`af_depreciacion`;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
